env:
  db:
    uri: jdbc:postgresql://${BEACON_API_DB_HOST:127.0.0.1}:5432/beacon_api
    username: ${BEACON_API_DB_USER_NAME:beaconapiuser}
    password: ${BEACON_API_DB_USER_PASSWORD:beaconuserpassword}

spring:
  application.name: beacon-api
  liquibase:
    enabled: false
    change-log: classpath:/db/changesets/changelog.xml

beaconapi:
  database:
    uri: ${env.db.uri}
    username: ${env.db.username}
    password: ${env.db.password}

logging.level.org.liquibase: DEBUG